In [4]:
from sklearn.linear_model import LinearRegression

# House size
X = [[1000], [1200], [1500], [1800]]

# House price (in lakh)
y = [4,5,6,8]

model = LinearRegression()
model.fit(X, y)

prediction = model.predict([[1600]])

print("Predicted Price:", prediction[0], "Lakh")

Predicted Price: 6.836734693877551 Lakh


In [10]:
from sklearn.linear_model import LinearRegression
# STUDENT HOUR
x =[[2],[3],[4]]
# marks
y = [[20],[60],[70]]
model = LinearRegression()
model.fit(x,y)
prediction = model.predict([[5]])

print("Predicted marks:", prediction[0])

Predicted marks: [100.]


In [19]:
from sklearn.linear_model import LogisticRegression

X = [
    [2],
    [3],
    [4],
    [5],
    [6],
    [7]
]

y = [
    0,
    0,
    0,
    1,
    1,
    1
]

model = LogisticRegression()

model.fit(X, y)

prediction = model.predict([[8]])

print(prediction)


[1]


In [42]:
import numpy as np
a= np.array ([10,20,30,40,50])
print(a.shape)
print(a)
print(a.size)
print(a.ndim)
print(a.dtype)
print(a.flatten())
print(a.reshape(5,1))
print(np.max(a))
print(np.min(a))
print(np.append(a,60))
print(np.insert(a,2,25))
print(np.sum(a))
print(np.mean(a))
print(np.median(a))
print(np.sort(a))
print(np.sort(a)[::-1])
print(np.sqrt(a))
print(np.square(a))
print(a[0])
print(a[0:3])
print(a+10)
print(a-10)
print(a*10)
print(a/10)
print(a//10)

(5,)
[10 20 30 40 50]
5
1
int32
[10 20 30 40 50]
[[10]
 [20]
 [30]
 [40]
 [50]]
50
10
[10 20 30 40 50 60]
[10 20 25 30 40 50]
150
30.0
30.0
[10 20 30 40 50]
[50 40 30 20 10]
[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]
[ 100  400  900 1600 2500]
10
[10 20 30]
[20 30 40 50 60]
[ 0 10 20 30 40]
[100 200 300 400 500]
[1. 2. 3. 4. 5.]
[1 2 3 4 5]


In [43]:
print(np.insert(a,2,25))

[10 20 25 30 40 50]


In [2]:
import pandas as pd

df = pd.read_csv("marks.txt")

print(df.iloc[:2])

   Roll No   Name  Maths  Physics  Chemistry  English  Computer  Total
0        1  Rahul     78       82         75       80        85    400
1        2   Aman     65       70         68       72        74    349


In [3]:
df[["Name","Total"]][:10]

,Name,Total
0,Rahul,400
1,Aman,349
2,Priya,446
3,Neha,393
4,Rohit,300
5,Sneha,430
6,Arjun,354
7,Pooja,475
8,Karan,407
9,Anjali,381
