In [16]:
%pip install numpy

In [18]:
import numpy as np
a = np.array([10,24,45,36])
print(a)


[10 24 45 36]


In [20]:
import numpy as np
a = np.array([10,24,45,36],dtype=float)
print(a)


[10. 24. 45. 36.]


In [2]:
import numpy as np
a = np.array(["ayushi", "raunak" ,"mattu"])
print(a)

['ayushi' 'raunak' 'mattu']


In [3]:
import numpy as np
a = np.array([10,24,45,36])
print(a)


[10 24 45 36]


In [9]:
import numpy as np
a = np.array([[10,24,45,36]
    ,[1,2,3,4]])
print(a)

[[10 24 45 36]
 [ 1  2  3  4]]


In [10]:
import numpy as np
a = np.array([[10,24,45,36]
    ,[1,2,3,4]])
print(a.ndim)

2


In [19]:
import numpy as np
a = np.array([
    [[10,24,45,36],[1,2,3,4]],
              [[12,34,67,78],[-9,92,92,67]],
              [[993,939,23,123],[23,45,7899,90]] 
])
print(a)

print(a.ndim)

[[[  10   24   45   36]
  [   1    2    3    4]]

 [[  12   34   67   78]
  [  -9   92   92   67]]

 [[ 993  939   23  123]
  [  23   45 7899   90]]]
3


In [21]:
import numpy as np
a = np.array([
    [[10,24,45,36],[1,2,3,4]],
              [[12,34,67,78],[-9,92,92,67]],
              [[993,939,23,123],[23,45,7899,90]] 
])
print(a)
print(a.ndim)
print(a.shape)

[[[  10   24   45   36]
  [   1    2    3    4]]

 [[  12   34   67   78]
  [  -9   92   92   67]]

 [[ 993  939   23  123]
  [  23   45 7899   90]]]
3
(3, 2, 4)


In [12]:
import numpy as np
a = np.ones((3,4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [9]:
a = np.eye((3))
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
a = np.full((3,4),2)
print(a)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [14]:
a = np.empty((3,4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [15]:
a = np.empty((3,3))
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [28]:
a = np.arange(1,13)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [30]:
a = np.arange(1,33,4 )
print(a)


[ 1  5  9 13 17 21 25 29]


In [35]:
b = a.reshape(4,2)
print(b)

[[ 1  5]
 [ 9 13]
 [17 21]
 [25 29]]


In [38]:
a = np.array([[34,67,78,89],[36,83,38,23]])
print(a)
print(a.flatten)

[[34 67 78 89]
 [36 83 38 23]]
[34 67 78 89 36 83 38 23]


In [39]:
a = np.array([34,67,78,89])
print(a[1])

67


In [43]:
a = np.array([34,67,55,89])
print(a[-2])

55


In [45]:
a = np.array([[34,67,78,89],[36,83,38,23]])
print(a[1,2])

38


In [53]:
a = np.array([
    
    [[12,34,45],[34,23,78]],
    [[56,78,67],[89,34,22]],
    [[34,89,23],[78,33,23]],
    [[93,89,23],[34,23,12]]
        
])
print(a[0,0])
print(a[0,1])
print(a[1,0])
print(a[1,1])
print(a[2,0])
print(a[2,1])
print(a[3,0])
print(a[3,1])

[12 34 45]
[34 23 78]
[56 78 67]
[89 34 22]
[34 89 23]
[78 33 23]
[93 89 23]
[34 23 12]


In [54]:
a = np.array([12,45,56])
b = np.array([67,99,100])
print(a+b)

[ 79 144 156]


In [55]:
a = np.array([12,45,56])
b = np.array([67,99,100])
print(a-b)

[-55 -54 -44]


In [56]:
a = np.array([12,45,56])
b = np.array([67,99,100])
print(b-a)

[55 54 44]


In [57]:
a = np.array([12,45,56])
b = np.array([67,99,100])
print(a*b)

[ 804 4455 5600]


In [58]:
a = np.array([12,45,56])
b = np.array([67,99,100])
print(a/b)

[0.17910448 0.45454545 0.56      ]


In [59]:
a = np.array([12,45,56])
b = np.array([67,99,100])
print(b/a)

[5.58333333 2.2        1.78571429]


In [60]:
a = np.array([12,45,56])

print(a^2)

[14 47 58]


In [61]:
a = np.array([12,45,56])

print(np.sqrt(a))



[3.46410162 6.70820393 7.48331477]


In [62]:

a = np.arange(1,21)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [63]:
a = np.zeros((4,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [64]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [74]:
a = np.arange(1,11)
print(a)
b = a.reshape(2,5)
print(b.shape)


[ 1  2  3  4  5  6  7  8  9 10]
(2, 5)


In [65]:
a = np.arange(1,13)
print(a)
b = a.reshape(3,4)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [68]:
a = np.array([12,23,56,90,1])
print(a.max())
print(a.min())

90
1


In [75]:
a = np.array([12,18,25,30,45])
mean = np.mean(a)
median = np.median(a)
std = np.std(a)
print(mean)
print(median)
print(std)


26.0
25.0
11.29601699715435


In [78]:
a = np.array([12,23,56,90,1])
sorted = np.sort(a)[::-1]
print(sorted)
b = np.sort(a)
print(b)

[90 56 23 12  1]
[ 1 12 23 56 90]


In [79]:
a = np.array([20,45,55,60,75])
print(a[a>50])

[55 60 75]


In [2]:
import numpy as np
a = np.arange(1,101)
b = np.random.randint(1,101,10)
print(b)

[100  99  81  26   4  80  70  56  49  52]


In [3]:
a = np.array([12,45,56])
print(np.sqrt(a))
print(np.abs(a))
print(np.exp(a))
print(np.log(a))
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))






[3.46410162 6.70820393 7.48331477]
[12 45 56]
[1.62754791e+05 3.49342711e+19 2.09165950e+24]
[2.48490665 3.80666249 4.02535169]
[-0.53657292  0.85090352 -0.521551  ]
[0.84385396 0.52532199 0.85322011]
[-0.63585993  1.61977519 -0.61127369]


In [4]:
a = np.array([10,20,30])
b = a.copy()  #original remAINS UNCHANGED
b[0] = 100 
print(a)
print(b)

[10 20 30]
[100  20  30]


In [5]:
a = np.array([10,20,30])
b = a.view()  #original CHANGED
b[0] = 100 
print(a)
print(b)

[100  20  30]
[100  20  30]


In [6]:
print(np.random.rand(5))
print(np.random.randint(1,101,10))
print(np.random.randint(1,101,(1,4)))


[0.82199557 0.55844778 0.78986258 0.49444669 0.19217718]
[59 96 71 65 95 56 37 11 76 60]
[[77 44 82 62]]


In [7]:
marks = np.array([12,23,45,67])
print(marks + 10)

[22 33 55 77]


In [9]:
a = np.array([[1,2],[3,4]])
print(a*4)

[[ 4  8]
 [12 16]]


In [10]:
marks = np.array([12,34,56,78])
print("average " ,np.mean(marks))
print("maximum " ,np.max(marks))
print("minimum " ,np.min(marks))


average  45.0
maximum  78
minimum  12


In [17]:
salary = np.array([
    34000,78000,53400,87730,738380,733830,452446,49884,93987,93794,
    98480,89767,76789,898868,87878,897979,99978,78303,983033,983093,
    380383,99484,9099393,7887983,3254346,5587686,86879,68698,78889,
    98033,9397393,892727,83983,398739,83733,90933
])
print("salaries :" , salary)
print("highest:" , max(salary))
print("lowest:" , min(salary))
print("average:" , sum(salary)/len(salary))

salary.sort()
print("sorted salary:" , salary)

increment =  0.1* salary
newsalary=  increment+ salary
print("after increment:" , newsalary)

print("increase:" , newsalary-salary)













salaries : [  34000   78000   53400   87730  738380  733830  452446   49884   93987
   93794   98480   89767   76789  898868   87878  897979   99978   78303
  983033  983093  380383   99484 9099393 7887983 3254346 5587686   86879
   68698   78889   98033 9397393  892727   83983  398739   83733   90933]
highest: 9397393
lowest: 34000
average: 1230525.0277777778
sorted salary: [  34000   49884   53400   68698   76789   78000   78303   78889   83733
   83983   86879   87730   87878   89767   90933   93794   93987   98033
   98480   99484   99978  380383  398739  452446  733830  738380  892727
  897979  898868  983033  983093 3254346 5587686 7887983 9099393 9397393]
after increment: [   37400.     54872.4    58740.     75567.8    84467.9    85800.
    86133.3    86777.9    92106.3    92381.3    95566.9    96503.
    96665.8    98743.7   100026.3   103173.4   103385.7   107836.3
   108328.    109432.4   109975.8   418421.3   438612.9   497690.6
   807213.    812218.    981999.7   987776.9  